GITHUB_USER=codewithvignesh-dev
GITHUB_REPO=Play-Integrity-Fixer

CHECK_INTERVAL=60

FILE_NAME=keybox.xml

DOWNLOAD_DIR=/data/local/tmp/integrityfixer

MODULE_DIR=/data/adb/modules/integrityfixer

FILE_PATH=$MODULE_DIR/data/adb/tricky_store

DOWNLOAD_URL=""

LAST_NOTIFIED_VERSION=0
LAST_NOTIFIED_DATE=""